name: Build and Publish AMI

on:
  push:
    branches:
      - main

jobs:
  build-ami:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.7.6/packer_1.7.6_linux_amd64.zip
          unzip packer_1.7.6_linux_amd64.zip
          sudo mv packer /usr/local/bin/
        if: success()

      - name: Initialize Packer
        run: packer init .

      - name: Verify Packer Version
        run: packer version

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region YOUR_REGION  # Replace YOUR_REGION with your desired region

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3

      - name: Run ami_build.py
        run: python ami_build.py
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
